### ISSUE TITLE
Determine Website Name

### ISSUE THREAD

**Issue by aubreyspannagel** [Kensleemoy/SeniorDesign#3]
As a developer, I want to have a name for my project.

**Comment by Kensleemoy** [comment]
Stick ideas into Google Drive document to reconvene and decide on a name on Tuesday 09/15

**Comment by aubreyspannagel** [comment]
COVID by County

**Comment by sbenda14** [comment]
Something that has idaho in it:

-Idaho covid tracking
-Covid in Idaho

**Comment by Kensleemoy** [comment]
COV-IDaho
